#!/bin/tcsh

set path_to_spx = $1
set path_to_profile_directory = $2
set out_file_basename = $3

setenv spineXcodir $path_to_spx

echo $out_file_basename > "$path_to_profile_directory/protein_list_file_$out_file_basename.txt"

$path_to_spx/spX.pl $path_to_profile_directory/protein_list_file_$out_file_basename.txt $path_to_profile_directory $path_to_profile_directory >/dev/null

cp $path_to_profile_directory/$out_file_basename.spXout $path_to_profile_directory/$out_file_basename.dis # workaround for iFeature bug

rm "$path_to_profile_directory/protein_list_file_$out_file_basename.txt"