import sys, os

print(os.getcwd())

# print(sys.path)
#
# sys.path.append(".")
#
# print(sys.path)

from peptidereactor.workflow_executer \
    import WorkflowExecuter
from nodes.utils.tertiary_structure_search.scripts.utils \
    import dump_structure_slice, get_seq_names

rule a:
    input:
         "1zr9.dssp"
    output:
         "1zr9_copy.dssp"
    shell:
         "cp {input} {output}"