name: utils_validate_sequence_names
env:
  channels:
    - bioconda
    - anaconda
    - conda-forge
  dependencies:
    - pip=19.2.3
    - python=3.7.4
    - snakemake-minimal=5.5.4
    - pip:
      - modlamp