from modlamp.core import read_fasta, save_fasta
import re

rule all:
    input:
        config["fasta_out"]

rule validate:
    input:
         config["fasta_in"]
    output:
         config["fasta_out"]
    run:
         seqs, names = read_fasta(str(input))
         names_new = [re.sub("[\W\s]", "", n) for n in names]
         save_fasta(str(output), seqs, names_new)
