from modlamp.core import read_fasta, save_fasta
import re
import numpy as np

rule all:
    input:
        config["fasta_out"]

rule validate:
    input:
         config["fasta_in"]
    output:
         config["fasta_out"]
    run:
         seqs, names = read_fasta(str(input))
         names_new = []
         for n in names:
             tmp = re.sub("[\W\s]", "", n)
             # check if truncated name is by chance already present
             # if yes, add random number
             if tmp in names_new:
                 tmp += str(np.random.randint(1000))
             names_new += [tmp]

         save_fasta(str(output), seqs, names_new)
