from modlamp.core import read_fasta

import os
os.environ["R_LIBS_USER"] = "."

rule generate_disorderb_encoding:
    input:
         "data/{dataset}/annotated_seqs_msa.fasta",
         "data/{dataset}/annotated_classes.txt"
    output:
          "data/{dataset}/csv/disorderb.csv"
    run:
        import encoder.ifeature.pssm.disprot_encoding.encoder as disprot_encoder
        seqs, names = read_fasta(str(input[0]))
        with open(str(input[1])) as f:
            classes = list(map(lambda l: int(l.rstrip()), f.readlines()))
        in_da = ([[n, s] for s, n in zip(seqs, names)], classes)
        df = disprot_encoder.DisorderBEncoder(in_data=in_da,
                                              profile_dir=f"data/{wildcards.dataset}/profile",
                                              cores=4,
                                              run_msa=False).encode()
        df.to_csv(str(output))

