from modlamp.core import read_fasta, save_fasta
import re


rule all:
    input:
        config["fasta_val"]


rule init:
    input:
        config["fasta"]
    output:
        temp("data/interim.fasta"),
    shell:
        """
        cp {input[0]} {output[0]}
        """


rule validate:
    input:
        "data/interim.fasta",
    output:
        config["fasta_val"]
    run:
        seqs, names = read_fasta(str(input[0]))
        names_new = [re.sub("[\W\s]", "", n) for n in names]
        save_fasta(str(output[0]), seqs, names_new)
