from modlamp.core import read_fasta, save_fasta
import re


rule all:
    input:
        config["output_file_0"],


rule init:
    input:
        config["input_file_0"],
        config["input_file_1"]
    output:
        temp("data/interim.fasta"),
        temp("data/interim_classes.txt")
    shell:
        """
        cp {input[0]} {output[0]}
        cp {input[1]} {output[1]}
        """


rule validate:
    input:
        "data/interim.fasta",
        "data/interim_classes.txt"
    output:
        config["output_file_0"]
    run:
        seqs, names = read_fasta(str(input[0]))
        names_new = [re.sub("[\W\s]", "", n) for n in names]
        save_fasta(str(output[0]), seqs, names_new)
