from modlamp.core import read_fasta, save_fasta
import yaml

rule all:
    input:
        config["fasta_out"],
        config["maps_out"]

rule map_names:
    input:
         config["fasta_in"]
    output:
         config["fasta_out"],
         config["maps_out"]
    run:
         seqs, _ = read_fasta(str(input))

         with open(str(input)) as f:
             names = [l.rstrip().replace(">", "") for l in f.readlines() if l.startswith(">")]

         names_new = [f"Seq_{i}" for i in range(1, len(names)+1)]

         save_fasta(str(output[0]), seqs, names_new)

         with open(str(output[1]), mode="w") as f:
             yaml.safe_dump(dict(zip(names_new, names)), f)




