#!/usr/bin/env bash

docker build -t peptidereactor peptidereactor/ --force-rm=true

if [ $? -eq 127 ]; then
  echo "Please install docker first (requires sudo privileges): ./peptidereactor/install_docker_[ce|io]"
fi
