name: peptidereactor-env
channels:
  - bioconda
  - anaconda
  - conda-forge
  - biocore
  - salilab
  - omnia
  - rdkit
  - mordred-descriptor
  - plotly
  - schrodinger
dependencies:
  - biopython=1.74
  - numpy=1.17.1
  - pip=19.2.3
  - python=3.7.4
  - scipy=1.3.1
  - scikit-learn
  - pandas
  - snakemake-minimal=5.19.0
  - blast=2.9.0
  - java-jdk
  - muscle=3.8.1551
  - modeller=9.25
  - openmm
  - rdkit
  - mordred=1.2.0
  - imbalanced-learn
  - pathos
  - more-itertools
  - plotly
  - graphviz
  - pymol
  - jinja2
  - pygraphviz
  - pygments
  - imagemagick
  - altair=4.1.0
  - flask=1.1.2
  - pip:
    - modlamp
    - joblib
    - pydevd-pycharm # https://github.com/JetBrains-Research/snakecharm/issues/137
    - -e iFeature
