name: encoding_benchmark
channels:
  - bioconda
  - anaconda
  - conda-forge
  - biocore
  - salilab
  - openbabel
dependencies:
  - biopython=1.74
  - numpy=1.17.1
  - pip=19.2.3
  - python=3.7.4
  - scipy=1.3.1
  - scikit-learn
  - pandas
  - snakemake-minimal=5.7.0
  - blast=2.9.0
  - java-jdk
  - muscle=3.8.1551
  - r-base
  - r-yaml
  - modeller=9.23
  - openbabel
  - pip:
    - modlamp
    - joblib
    - -e iFeature