#!/usr/bin/env sh

sudo apt install docker.io

echo "Adding $USER to docker group..."
sudo usermod -aG docker $USER

echo "Installation finished. Please log out and log back in " \
     "so that your group membership is re-evaluated."
