#!/usr/bin/env bash

smk_args=$@

if docker image inspect encoding_benchmark > /dev/null 2>&1; then
  docker run -v $PWD:/snakemake \
           -v $PWD/data:/snakemake/data \
           -v $DB_DIR:/snakemake/db_tmp \
           -u `id -u $USER` \
           encoding_benchmark $smk_args
  rm -rf db_tmp/
else
  echo "Image for encoding_benchmark not found. Please create image first: ./docker/build_image"
  exit 1
fi