name: encodings_paac
channels:
    - bioconda
    - anaconda
    - conda-forge
    - biocore
  dependencies:
    - biopython
    - numpy=1.17.1
    - pip=19.2.3
    - python=3.7.4
    - scipy=1.3.1
    - snakemake-minimal=5.5.4
    - r-base
    - pip:
      - modlamp